-- Supabase SQL Schema Definitions

-- 1. Profiles Table (sync with auth.users)
create table public.profiles (
  id uuid not null references auth.users on delete cascade,
  email text,
  username text,
  avatar_url text,
  role text default 'user',
  store_id integer,
  updated_at timestamp with time zone,
  
  primary key (id),
  constraint username_length check (char_length(username) >= 3)
);

alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- 2. Messages Table
create table public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  user_email text,
  content text check (char_length(content) > 0),
  channel_id text default 'general',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.messages enable row level security;

create policy "Everyone can read messages"
  on messages for select
  using ( true );

create policy "Authenticated users can insert messages"
  on messages for insert
  with check ( auth.role() = 'authenticated' );

-- 3. Automatic Message Cleanup Function (1 Year Retention)
create or replace function delete_old_messages()
returns void
language plpgsql
as $$
begin
  delete from public.messages
  where created_at < now() - interval '1 year';
end;
$$;

-- 4. Enable Realtime
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime for table messages;
commit;

-- 5. Trigger for New User (Optional)
create or replace function public.handle_new_user() 
returns trigger 
language plpgsql 
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, username)
  values (new.id, new.email, new.raw_user_meta_data ->> 'username');
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
